# Generated by Django 5.0.6 on 2024-07-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contenu',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='titre',
        ),
    ]
