# Generated by Django 5.0.6 on 2024-07-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_category_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(default='Non spécifié', max_length=100),
        ),
    ]
