# Generated by Django 5.0.6 on 2024-08-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
