# Generated by Django 5.0.6 on 2024-08-05 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='validated',
        ),
    ]
