# Generated by Django 5.0.6 on 2024-08-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
