# Generated by Django 5.0.6 on 2024-08-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='predicted_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
